spring.datasource.url=jdbc:mysql://${AEGIS_DB_HOST:localhost}:${AEGIS_DB_PORT:3306}/${AEGIS_DB_NAME:aegis}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${AEGIS_DB_USER:aegis}
spring.datasource.password=${AEGIS_DB_PASS:aegis}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update